title: "Lexical Semantic Change: Models, Data and Evaluation"
description: "Tutorial LREC 2022 - Monday 20 June, 2022 <br> 9 am - 1 pm <br> Room 12 - Palais du Pharo (Marseille, France)"
theme: jekyll-theme-cayman
