title: "Lexical Semantic Change: Models, Data and Evaluation"
description: "Tutorial LREC 2022 - Monday 20 June, 2022 <br> 9 am - 1 pm <br> <a href=""https://lrec2022.lrec-conf.org/en/conference-venue/palais-pharo/pharo-floor-maps"">Room Petit Mucem - Palais du Pharo (Marseille, France)</a>
"
theme: jekyll-theme-cayman
